export const ActionTypes = {
    SET_PETS: "SET_PETS",
    SET_USER: 'SET_USER',
    SET_SELECTED_PET: "SET_SELECTED_PET",
    REMOVE_SELECTED_PET: "REMOVE_SELECTED_PET",
    NAV_LOGIN: 'NAV_LOGIN',
    SET_CATEGORISED_PETS: "SET_CATEGORISED_PETS",
    SEARCH: 'SEARCH',
    SET_USER_POST: 'SET_USER_POST',
    SET_CROPPED_IMAGE: 'SET_CROPPED_IMAGE'

}