export const ActionTypes={
    SET_PETS : "SET_PETS",
    SET_USER : 'SET_USER',
    SET_SELECTED_PET : "SET_SELECTED_PET",
    REMOVE_SELECTED_PET : "REMOVE_SELECTED_PET",
    NAV_CREATE:'NAV_CREATE',
    NAV_LOGIN:'NAV_LOGIN',
    SEARCH:'SEARCH'
}